# Generated by Django 4.1 on 2023-04-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_url', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('house_name', models.CharField(max_length=200)),
                ('house_status', models.CharField(max_length=200)),
                ('house_type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('district', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('sur_trafic', models.CharField(max_length=200)),
                ('sur_school', models.CharField(max_length=200)),
                ('sur_environment', models.CharField(max_length=200)),
                ('sur_business', models.CharField(max_length=200)),
                ('sur_entertain', models.CharField(max_length=200)),
                ('peoperty_fee', models.CharField(max_length=200)),
                ('property_company', models.CharField(max_length=200)),
            ],
        ),
    ]
