# Generated by Django 4.1 on 2023-04-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_new_sub_div_div_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_new',
            name='s_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.sub_div'),
        ),
    ]
