# Generated by Django 4.1 on 2023-04-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_sub_div_old_alter_listing_new_s_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_div',
            name='div_id',
            field=models.CharField(max_length=200),
        ),
    ]
