# Generated by Django 4.1 on 2023-04-27 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_sub_div_div_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_div',
            old_name='div_id',
            new_name='new_div_id',
        ),
    ]
